# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981650b822591d429ee32c1800f8e606e032e1ebddd1d0e1447b7d44d4de889356431e4a1f2d514768526eb4a3709962c904081691226eb348e719578ddcaac5

test:
  secret_key_base: cd8f5eb53e81ad1c49268aabf912e460a410ee3d0ac2fa83a602cbdab6d643465b495fc7a8bd48b0a8c7a1834ccd2e7c5e5885f845a9967a95d4b94481343eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
